services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermarketdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"  # Porta para o RabbitMQ
      - "15672:15672"  # Porta para acessar o painel de controle do RabbitMQ
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supermarketpetize-container
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/supermarketdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
